spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: "root"
    password: "041012"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.back.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: true
    map-underscore-to-camel-case: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    use-generated-keys: true
server:
  port: 8082



